[package]
name = "mli"
version = "0.5.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
rand = "0.3.13"
num = "0.1.30"
collenchyma = "0.0.7"
collenchyma-nn = { git = "https://github.com/autumnai/collenchyma-nn" }
