[workspace]

members = [
    "mli",
    "mli-ndarray",
    "mli-relu",
    "mli-conv",
    "mli-sigmoid",
    "mli-defconv",
    "mli-dense",
    "examples/sobel",
    "examples/deep-train",
    "examples/mnist",
]
