[package]
name = "mli-ndarray"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
mli = { path = "../mli", version = "0.11.0" }
ndarray = "0.12.1"
itertools = "0.8.0"
